name: MSBuild

on:
  
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:

  build:  
    name: ${{ matrix.os }} ${{ matrix.platform }} ${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        platform: [x86, x64]
        configuration: [Debug, Release]

    steps:
  
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Run MSBuild
        run: msbuild RetroStudio/RetroStudio.sln -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: RetroStudio-${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.configuration }}
          path: |
              RetroStudio/${{ matrix.platform }}/${{ matrix.configuration }}/RetroStudio.exe
